### ISSUE TITLE
FrameWork does not show any file

### ISSUE THREAD

**Issue by Nitish34** [HUYU2048/PTFakeTouch#12]
<img width="1402" alt="screen shot 2018-07-16 at 11 33 45 am" src="https://user-images.githubusercontent.com/9015460/42744736-34201906-88ec-11e8-81b3-eec5724b9523.png">

Whenever I try to include framework in my project it does not show or give suggestion about .h file.
My os Version is 11.0 & I am using swift 4 / Objective c.

**Comment by xuanxt** [comment]
1.Do not build it with simulator.
2.Try to build it after type completed '#import <PTFakeTouch/PTFakeTouch.h>'

**Comment by Nitish34** [comment]
I am building it, by keeping Generic iOS device mode. And then I get framework in product folder of PTFaketouch project. But PTFaketouch.framework file shows info.plist, modules, PTFaketouch file. And when I include this framework in my new project it only shows framework with no header files in that.

**Comment by xuanxt** [comment]
I updated project's headers setting,you can git pull the newest project.

**Comment by Nitish34** [comment]
OK will check, And also I am upgrading deployment target to 11.0, so that will not be any issue and my target os will 11+ only
