### ISSUE TITLE
Files Does not work in iOS 11 devices

### ISSUE THREAD

**Issue by Nitish34** [HUYU2048/PTFakeTouch#13]
I have integrated framework of PTFakeTouch, when I run it on device it shows **error** saying **"Code sign error : bundle format unrecognized, invalid, or unsuitable"**, and when I run the same in simulator it says **error: Invalid bitcode signature, and gives warning  missing required architecture x86_64 in IOKIT.framework**. 

I have included PTFakeTouch.Framework & IOKit.Framework in my project, which I got when I build the PTFakeTouch project. **I have just added the team in your project.** 

And rest everything was same, as mentioned in your GitHub link.

**Comment by xuanxt** [comment]
It doesn't seem to be a issue with my project.It works fine on my computer.

**Comment by sliverblack** [comment]
Hi, I add PTFakeTouch to my Tweak, when I send touch is crash, please help

**Comment by xuanxt** [comment]
@sliverblack What the app you inject?

**Comment by sliverblack** [comment]
hi HUYU2048, I want auto touch screen.

NSString *xx=[dict objectForKey:@"xx"];
                                        NSString *yy=[dict objectForKey:@"yy"];
                                        int x=[xx integerValue];
                                        int y=[yy integerValue];
                                        NSInteger pointId = [PTFakeMetaTouch fakeTouchId:[PTFakeMetaTouch getAvailablePointId] AtPoint:CGPointMake(x,y) withTouchPhase:UITouchPhaseBegan];
                                        [PTFakeMetaTouch fakeTouchId:pointId AtPoint:CGPointMake(x,y) withTouchPhase:UITouchPhaseEnded];

It not touch screen. :(
