### ISSUE TITLE
对源码有点疑问

### ISSUE THREAD

**Issue by laoyur** [HUYU2048/PTFakeTouch#14]
1. 这个项目跟 https://github.com/louisdh/pointerkit/tree/master/PTFakeTouch-master%202 的关系是？
2. 不明白为何作如下设计：

```
+ (void)load{
    KW_ENABLE_CATEGORY(UITouch_KIFAdditions);
    KW_ENABLE_CATEGORY(UIEvent_KIFAdditions);
    touchAry = [[NSMutableArray alloc] init];
    for (NSInteger i = 0; i<100; i++) {
        UITouch *touch = [[UITouch alloc] initTouch];
        [touch setPhaseAndUpdateTimestamp:UITouchPhaseEnded];
        [touchAry addObject:touch];
    }
}
```
为何要在load的时候预先制造100个UITouch对象出来，为了之后的点击复用？防止每次创建新的对象？
如果是这样的话，创建100个，为何在getAvailablePointId时又只用到50个？
```
    for (NSInteger i=0; i<touchAry.count-50; i++) {
        UITouch *touch = [touchAry objectAtIndex:i];
        if (touch.phase==UITouchPhaseEnded||touch.phase==UITouchPhaseStationary) {
            [availableIds addObject:@(i+1)];
        }
    }
```
<del>上面的代码还有个疑问，UITouchPhaseStationary阶段的UITouch拿出去复用真的好吗？如果把它复用成UITouchPhaseBegan，逻辑不通啊</del> <--- 看错了，这里没问题，后面在复用成UITouchPhaseBegan的时候会重新创建新的UITouch对象

**Comment by xuanxt** [comment]
1:他用我的代码做的修改，你看COMMIT历史可以看的出来。（我会给他发邮件）
2:这个设计是有点问题，以前做的时候没考虑到性能问题。（有空的话可能会修改）

**Comment by laoyur** [comment]
感谢答复。
怼他！哈哈
