### ISSUE TITLE
Compile with theos

### ISSUE THREAD

**Issue by eeeewwqq** [HUYU2048/PTFakeTouch#15]
Did somebody try to compile this lib with theos? I was trying to compile it from ios device, but seem it impossible. XCTest/XCTest.h required, this is one of xcode frameworks I think.

![image](https://user-images.githubusercontent.com/32315776/43995784-d2ac6ca6-9dbd-11e8-889c-a76c70d3ebc0.png)

I think the only way to compile this lib is xcode? Is it possible to use this lib at tweak? Compile dylib?

**Comment by xuanxt** [comment]
You must build compile this with xcode, You shoud delete the Test target If you want to compile this with make.
You can use this Framework at tweak .
