### ISSUE TITLE
导入失败，太简陋了，可以详细一点吗

### ISSUE THREAD

**Issue by ghost** [HUYU2048/PTFakeTouch#18]

**Comment by xuanxt** [comment]
不好意思，我没看明白您怎么导入失败，可以描述的详细一点吗？

**Comment by ghost** [comment]
只需要导入这个PTFakeTouch.framwork吗，然后头文件引用是什么，然后试了头文件，发现你给的例子报错没找到类，解决了例子报错，又报错symbol(s) not found for architecture arm64

**Comment by xuanxt** [comment]
导入工程里面的IOKit

**Comment by ghost** [comment]
加了，但感觉和没加没区别啊，还是一样的错误

**Comment by xuanxt** [comment]
什么symbol没有找到

**Comment by aishuidedabai** [comment]
<img width="1174" alt="2019-02-14 1 06 07" src="https://user-images.githubusercontent.com/18343966/52764233-23f59e00-305a-11e9-97bb-3c9bfe85d3b2.png">

**Comment by ghost** [comment]
<img width="1159" alt="2019-02-14 1 12 37" src="https://user-images.githubusercontent.com/18343966/52764261-41c30300-305a-11e9-9cac-53ed1a083a6c.png">

**Comment by ghost** [comment]
你看下是哪里不对。。

**Comment by xuanxt** [comment]
你编译成模拟器架构的了？

**Comment by ghost** [comment]
是的，需要全部是真机架构？

**Comment by xuanxt** [comment]
对，而且是[PTFakeMetaTouch fake.....]不是PTFakeTouch，仔细看头文件
