### ISSUE TITLE
Non-public API usage 

### ISSUE THREAD

**Issue by Rcrosp** [HUYU2048/PTFakeTouch#19]
--
 
Dear Developer,We identified one or more issues with a recent delivery for your app, "XXXX. Please correct the following issues, then upload again. Non-public API usage - The app references non-public symbols in XXXMoudle: _IOHIDEventAppendEvent, _IOHIDEventCreateDigitizerEvent, _IOHIDEventCreateDigitizerFingerEventWithQuality, _IOHIDEventSetIntegerValue. If method names in your source code match the private Apple APIs listed above

**Comment by xuanxt** [comment]
Yeah, It not allowed by appstore.
