### ISSUE TITLE
crash in iOS 14

### ISSUE THREAD

**Issue by Fordeson** [HUYU2048/PTFakeTouch#22]

**Comment by HongYuuu** [comment]
@implementation UITouch (KIFAdditions)  里边的东西备注掉就能用了ios14

**Comment by gr3atest** [comment]
For anyone having this issue, I created a pull request: https://github.com/Ret70/PTFakeTouch/pull/23 with the solution. If this isn't merged yet, feel free to clone the forked repo in the meantime

**Comment by gr3atest** [comment]
IOS14 support now in master branch, this can be closed

**Comment by xuanxt** [comment]
Thanks gr3atest 🙏
