### ISSUE TITLE
Keyboard click

### ISSUE THREAD

**Issue by LevkovichArtem** [HUYU2048/PTFakeTouch#3]
Hi man! Thank you for these samples!
Do you have an idea - why click doesn't work for keyboard?
Keyboard just disappears.
And maybe do you know - how to fix it?

**Comment by LevkovichArtem** [comment]
Oh, i fixed it, if it will be interesting for someone - ping me.

**Comment by xuanxt** [comment]
@ArtemLevkovichBLR How did you fixed id? can you pull requests,thanks!

**Comment by LevkovichArtem** [comment]
@PugaTang could you please create non-protected Development branch for it?

**Comment by xuanxt** [comment]
@ArtemLevkovichBLR OK,I created a new branch.

**Comment by LevkovichArtem** [comment]
@PugaTang, done, please check
