### ISSUE TITLE
集成到项目中是否可以通过App Store审核

### ISSUE THREAD

**Issue by loufq** [HUYU2048/PTFakeTouch#6]
集成到项目中是否可以通过App Store审核

**Comment by xuanxt** [comment]
当然不可以，iOKit是禁止使用的。
但是可以绕过

**Comment by linziyiwj** [comment]
> 当然不可以，iOKit是禁止使用的。 但是可以绕过

请问下项目中是不能集成 IOKit 吗，怎么绕过呢
