### ISSUE TITLE
集成到xocode8报错

### ISSUE THREAD

**Issue by DebugAlvin** [HUYU2048/PTFakeTouch#8]
ld: warning: ignoring file /Users/Alvin/Downloads/PTFakeTouch-master/IOKit.framework/IOKit.tbd, missing required architecture x86_64 in file /Users/Alvin/Downloads/PTFakeTouch-master/IOKit.framework/IOKit.tbd (3 slices)
Undefined symbols for architecture x86_64:
  "_IOHIDEventCreateDigitizerEvent", referenced from:
      _kif_IOHIDEventWithTouches in PTFakeTouch(IOHIDEvent+KIF.o)
  "_IOHIDEventCreateDigitizerFingerEventWithQuality", referenced from:
      _kif_IOHIDEventWithTouches in PTFakeTouch(IOHIDEvent+KIF.o)
  "_IOHIDEventSetIntegerValue", referenced from:
      _kif_IOHIDEventWithTouches in PTFakeTouch(IOHIDEvent+KIF.o)
  "_IOHIDEventAppendEvent", referenced from:
      _kif_IOHIDEventWithTouches in PTFakeTouch(IOHIDEvent+KIF.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xuanxt** [comment]
import IOKit
